### ISSUE TITLE
flake8 warning: F821 undefined name 'dimss

### ISSUE THREAD

**Issue by thoroc** [wl-zhao/UniPC#3]
This is the line: https://github.com/wl-zhao/UniPC/blob/f3658f209352d72ede9eb82292c93e144ffc07cc/example/stable-diffusion/ldm/models/diffusion/uni_pc/uni_pc.py#L679.

I have looked at the method definition and it looks like the variable `dimss` might be misspelled.

**Comment by wl-zhao** [comment]
Thanks for your careful reading! The typo has been fixed.
