### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by space-nuko** [wl-zhao/UniPC#4]
Hi, I was wondering if we could integrate your code in the stable-diffusion-webui project. That project is licensed AGPL3, but there is no license in this repository. Would we have permission to use your code?

**Comment by wl-zhao** [comment]
That is great!  Actually, I have noticed your [pull request](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/7710#issue-1579636272) and the good results. Thanks for your efforts in integrating UniPC to stable-diffusion-webui project.
