### ISSUE TITLE
R_p(h) in the paper might be inconsistent with the implementation in the code

### ISSUE THREAD

**Issue by Zheng222** [wl-zhao/UniPC#5]
@wl-zhao In the paper, Theorem 3.1 shows ${R_p}{\left( h \right)_{p,p}} = {\left( {{r_p}h} \right)^{p - 1}}$. But   

https://github.com/wl-zhao/UniPC/blob/a54e61e6a5b860c62678f45a8d1d9af0ea0eef69/example/stable-diffusion/ldm/models/diffusion/uni_pc/uni_pc.py#L626
shows ${R_p}{\left( h \right)_{p,p}} = {\left( {{r_p}} \right)^{p - 1}}$.

**Comment by wl-zhao** [comment]
Hi, thanks for your interest in our work!

Actually, the two versions are equivalent. The definition in the paper makes it easier to give the condition in Equation (5) (and make the theoretical proof clearer), while the implementation in the code is more efficient.

Feel free to ask if you still have any questions.

Best,
Wenliang

**Comment by Zheng222** [comment]
> Hi, thanks for your interest in our work!
> 
> Actually, the two versions are equivalent. The definition in the paper makes it easier to give the condition in Equation (5) (and make the theoretical proof clearer), while the implementation in the code is more efficient.
> 
> Feel free to ask if you still have any questions.
> 
> Best, Wenliang

Thank you for your quick reply.
Changing
```
R.append(torch.pow(rks, i - 1))
```
to
```
R.append(torch.pow(rks*h, i-1))
```
will not significantly increase the computational cost.
Therefore, Is ${R_p}{\left( h \right)_{p,p}} = {\left( {{r_p}} \right)^{p - 1}}$ considered for numerical stability?

**Comment by wl-zhao** [comment]
Sorry for the confusion. It's not about the computational cost. Actually, our algorithm is initially designed as implemented in the code. We just use an equivalent form in the paper for the sake of a clearer presentation. We didn't test the numerical stability of the two methods. But I think using $R_{p, p}=r_p^{p-1}$ is indeed more stable, especially when there are more timesteps such that $h$ is too small.

**Comment by Zheng222** [comment]
> Sorry for the confusion. It's not about the computational cost. Actually, our algorithm is initially designed as implemented in the code. We just use an equivalent form in the paper for the sake of a clearer presentation. We didn't test the numerical stability of the two methods. But I think using Rp,p=rpp−1 is indeed more stable, especially when there are more timesteps such that h is too small.

Thank you very much for your answer！
